[Blog] Update hyperlink references for 3rd parties
segrowth/segrowth.github.io pull request #9
Opened 2024-07-20 17:26 UTC by KrzysiekJodlowski

Trello item: [Update hyperlink references for 3rd parties on blog pages](https://trello.com/c/7B8EwE0s/88-update-hyperlink-references-for-3rd-parties-on-blog-pages)

This commit:
- updates GitHub and Twitter usernames, adds YouTube username in the config
- adds YouTube contact and sidebar option
- disables unused RSS feed in the config

After checking, I see the e-mail reference works fine already - in my case, it opens Outlook with the correct e-mail address:

![admin_seg_dev_email](https://github.com/user-attachments/assets/6f205482-157d-459f-9cf8-4e1a1d2eb76e)

Currently the side bar looks as follows:

![seg_sidebar_updated](https://github.com/user-attachments/assets/b375fe28-2ae6-448d-951f-68ccf733b99e)

2024-07-22 06:05 UTC, the-sloth-dev requested changes

2024-07-22 06:05 UTC, the-sloth-dev commented on _data/contact.yml
> +# - type: rss
Bring this back we need it.

2024-07-22 16:25 UTC, KrzysiekJodlowski commented on _data/contact.yml
> +# - type: rss
@the-sloth-dev the RSS feed has been brought back:

![bringing_back_the_rss](https://github.com/user-attachments/assets/6a865310-e42c-4604-a40a-cbbd25f2c439)

2024-07-26 05:40 UTC, the-sloth-dev approved these changes

2024-07-26 05:41 UTC, merged